package home

import (
	"fmt"
	"net/http"
	"strings"

	"mu/internal/origin"
	"mu/internal/settings"
)

const toolsDescription = "Tools for agents"

// IsToolsHost reports whether the request came through the optional tools host.
// The host is only a second public identity for this same Mu process; it does
// not enable, disable or partition any tools.
func IsToolsHost(r *http.Request) bool { return origin.IsToolsHost(r) }

// ToolsIndex is the machine-first front page for the optional tools hostname.
// It deliberately has no Mu HTML shell, navigation or styling: this hostname is
// an entry point for callers that want protocols and capabilities, not the app.
func ToolsIndex(w http.ResponseWriter, r *http.Request) {
	name := toolsName()
	base := strings.TrimRight(origin.URL(r), "/")
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	fmt.Fprintf(w, "%s\n%s\n\n", name, toolsDescription)
	fmt.Fprintf(w, "MCP: %s/mcp\n", base)
	fmt.Fprintf(w, "Tools: %s/tools\n", base)
	fmt.Fprintf(w, "API: %s/api/v1/\n", base)
	fmt.Fprintf(w, "LLMs: %s/llms.txt\n", base)
	fmt.Fprintln(w, "\nPriced calls use HTTP 402/x402. MCP tools/list is the canonical live catalogue.")
}

// toolsName is deliberately derived rather than configured. A tools hostname
// is the operator's machine-facing identity: m3o.com becomes M3O, foobar.com
// becomes FOOBAR. A normal one-host Mu install has no second identity to name.
func toolsName() string {
	v := strings.TrimSpace(settings.Get("TOOLS_HOST"))
	if v == "" {
		return "Mu"
	}
	v = strings.TrimPrefix(strings.TrimPrefix(v, "https://"), "http://")
	if i := strings.IndexByte(v, '/'); i >= 0 {
		v = v[:i]
	}
	if i := strings.IndexByte(v, ':'); i >= 0 {
		v = v[:i]
	}
	parts := strings.Split(v, ".")
	if len(parts) >= 2 {
		return strings.ToUpper(parts[len(parts)-2])
	}
	if v != "" {
		return strings.ToUpper(v)
	}
	return "Mu"
}

// llms.txt is generated by Mu rather than maintained beside a deployment. The
// registry itself remains canonical at /tools and /api/v1/; this file gives an
// agent the stable entry points and tells it where to discover the live list.
func init() {
	http.HandleFunc("/llms.txt", func(w http.ResponseWriter, r *http.Request) {
		base := strings.TrimRight(origin.URL(r), "/")
		name := "Mu"
		description := "Open source agent runtime"
		if IsToolsHost(r) {
			name = toolsName()
			description = toolsDescription
		}
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		fmt.Fprintf(w, "# %s\n\n%s\n\n", name, description)
		fmt.Fprintf(w, "- MCP: %s/mcp\n", base)
		fmt.Fprintf(w, "- Tools: %s/tools\n", base)
		fmt.Fprintf(w, "- API catalogue: %s/api/v1/\n", base)
		fmt.Fprintf(w, "\nPriced calls use HTTP 402/x402. Discover the current tool names, descriptions and schemas with MCP tools/list.\n")
	})
}
