package home

import (
	"fmt"
	"html"
	"net/http"
	"strings"

	"mu/internal/app"
	"mu/internal/origin"
	"mu/internal/settings"
)

const toolsDescription = "Infrastructure for agents"

// IsToolsHost reports whether the request came through the optional tools host.
// The host is only a second public identity for this same Mu process; it does
// not enable, disable or partition any tools.
func IsToolsHost(r *http.Request) bool { return origin.IsToolsHost(r) }

// ToolsIndex is the lightweight front page for the optional tools hostname.
// Everything linked here is served by the same Mu instance.
func ToolsIndex(w http.ResponseWriter, r *http.Request) {
	name := toolsName(r)
	base := strings.TrimRight(origin.URL(r), "/")
	body := `<div class="lwrap">` +
		`<div class="lbrand">` + html.EscapeString(name) + `</div>` +
		`<div class="lwhat">` + toolsDescription + `</div>` +
		`<div style="margin-top:28px;line-height:2">` +
		`<a href="/tools">Tools</a> · ` +
		`<a href="/mcp">MCP</a> · ` +
		`<a href="/api/v1/">API</a> · ` +
		`<a href="/llms.txt">llms.txt</a>` +
		`</div>` +
		`<p style="margin-top:22px;color:#777;font-size:14px">` +
		`MCP: <code>` + html.EscapeString(base+"/mcp") + `</code></p>` +
		`</div>`

	page := app.RenderIndex(app.Index{
		Title:       name,
		Description: toolsDescription,
		Body:        body,
		Footer:      app.FooterLinks(),
	})
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache, private")
	_, _ = w.Write([]byte(page))
}

func toolsName(r *http.Request) string {
	if v := strings.TrimSpace(settings.Get("TOOLS_NAME")); v != "" {
		return v
	}
	if v := strings.TrimSpace(settings.Get("TOOLS_HOST")); v != "" {
		v = strings.TrimPrefix(strings.TrimPrefix(v, "https://"), "http://")
		if i := strings.IndexByte(v, '/'); i >= 0 {
			v = v[:i]
		}
		return v
	}
	return "Tools"
}

// llms.txt is generated by Mu rather than maintained beside a deployment. The
// registry itself remains canonical at /tools and /api/v1/; this file gives an
// agent the stable entry points and tells it where to discover the live list.
func init() {
	http.HandleFunc("/llms.txt", func(w http.ResponseWriter, r *http.Request) {
		base := strings.TrimRight(origin.URL(r), "/")
		name := "Mu"
		description := "Open source agent runtime"
		if IsToolsHost(r) {
			name = toolsName(r)
			description = toolsDescription
		}
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		fmt.Fprintf(w, "# %s\n\n%s\n\n", name, description)
		fmt.Fprintf(w, "- MCP: %s/mcp\n", base)
		fmt.Fprintf(w, "- Tools: %s/tools\n", base)
		fmt.Fprintf(w, "- API catalogue: %s/api/v1/\n", base)
		fmt.Fprintf(w, "\nPriced calls use HTTP 402/x402. Discover the current tool names, descriptions and schemas from /tools or the MCP tools/list method.\n")
	})
}
