import catalogue from "./catalog.json";
export { catalogue };
import { Mail as App0 } from "./mail";
import { SMS as App1 } from "./sms";
import { Notifications as App2 } from "./notify";
import { People as App3 } from "./users";
import { Chat as App4 } from "./chat";
import { Contacts as App5 } from "./contacts";
import { Events as App6 } from "./events";
import { Files as App7 } from "./files";
import { Tasks as App8 } from "./tasks";
import { MapApp as App9 } from "./maps";
import { Images as App10 } from "./images";
import { WebSearch as App11 } from "./web";
import { App as App12 } from "./archive";
import { App as App13 } from "./blog";
import { App as App14 } from "./bookmarks";
import { App as App15 } from "./browser";
import { App as App16 } from "./docs";
import { App as App17 } from "./flights";
import { App as App18 } from "./food";
import { App as App19 } from "./hazards";
import { App as App20 } from "./markets";
import { App as App21 } from "./news";
import { App as App22 } from "./notes";
import { App as App23 } from "./places";
import { App as App24 } from "./prayer";
import { App as App25 } from "./recall";
import { App as App26 } from "./routes";
import { App as App27 } from "./shell";
import { App as App28 } from "./social";
import { App as App29 } from "./stream";
import { App as App30 } from "./text";
import { App as App31 } from "./transit";
import { App as App32 } from "./video";
import { App as App33 } from "./weather";
const applications = {"mail": App0,"sms": App1,"notify": App2,"users": App3,"chat": App4,"contacts": App5,"events": App6,"files": App7,"tasks": App8,"maps": App9,"images": App10,"web": App11,"archive": App12,"blog": App13,"bookmarks": App14,"browser": App15,"docs": App16,"flights": App17,"food": App18,"hazards": App19,"markets": App20,"news": App21,"notes": App22,"places": App23,"prayer": App24,"recall": App25,"routes": App26,"shell": App27,"social": App28,"stream": App29,"text": App30,"transit": App31,"video": App32,"weather": App33};
export function Application({name}: {name:string}) { const Component = applications[name as keyof typeof applications]; return Component ? <Component /> : null; }
