package apps

import (
	"encoding/json"
	"fmt"
	htmlpkg "html"
	"strings"

	"mu/internal/quota"
)

// slugify turns a name into a URL-safe slug.
func slugify(s string) string {
	s = strings.ToLower(s)
	// Replace non-alphanumeric with hyphens
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') {
			b.WriteRune(c)
		} else if c == ' ' || c == '-' || c == '_' {
			b.WriteRune('-')
		}
	}
	result := strings.Trim(b.String(), "-")
	if len(result) > 50 {
		result = result[:50]
	}
	return strings.Trim(result, "-")
}

// editPageHTML renders the app editor: a code editor with live preview and a
// save bar. It is a manual editor — apps are generated by the constrained
// micro-app generator, but their HTML can still be hand-edited here.
func editPageHTML(a *App) string {
	state, _ := json.Marshal(map[string]any{"html": a.HTML, "name": a.Name, "description": a.Description, "tags": a.Tags, "icon": a.Icon, "slug": a.Slug, "public": a.Public, "price": a.Price})

	// Ask-for-a-change panel. Editing the stored spec keeps everything the
	// instruction does not mention; regenerating from a description would not.
	aiPanel := fmt.Sprintf(`<form method="POST" action="/apps/%s/ai-edit" class="form ai-edit">
  <label for="instruction">Change it with AI</label>
  <div class="form-row">
    <input type="text" id="instruction" name="instruction" required
           placeholder="e.g. add a Notes field, or change the total to average">
    <button type="submit">Apply</button>
  </div>
  <p class="ai-edit-note">%d credits. Your current version is saved first — undo any change from <a href="/apps/%s/versions">versions</a>.</p>
</form>`, htmlpkg.EscapeString(a.Slug), quota.OperationCost(quota.OpAppEdit), htmlpkg.EscapeString(a.Slug))

	savedAt := "Last saved " + a.UpdatedAt.Format("2 Jan 2006 15:04")
	versionLink := ""
	if len(a.Versions) > 0 {
		v := a.Versions[len(a.Versions)-1]
		versionLink = fmt.Sprintf(`<a href="/apps/%s/versions" class="text-muted">v%d · %d versions</a>`,
			htmlpkg.EscapeString(a.Slug), v.Number, len(a.Versions))
	}

	return fmt.Sprintf(`


<div class="builder">
  <div class="d-flex between items-center mb-1 flex-wrap gap-2">
    <p class="card-desc m-0">Edit your app</p>
    <div class="d-flex gap-2 items-center text-sm">
      <a href="/apps/%s" class="mini-btn">Open App</a>
      <button data-app-action="deleteApp" class="mini-btn btn-danger">Delete</button>
    </div>
  </div>

  %s

  <div class="editor-layout">
    <div class="ed-grow">
      <div class="code-header mb-2">
        <h3>Code</h3>
        <div class="form-actions">
          <button class="mini-btn" data-app-action="copyCode">Copy</button>
        </div>
      </div>
      <textarea data-preview-target="preview" class="code-editor ed-tall" id="code" spellcheck="false"></textarea>
    </div>
    <div class="ed-grow">
      <div class="preview-header mb-2">
        <h3>Preview</h3>
        <button class="mini-btn" data-app-action="updatePreview">Refresh</button>
      </div>
      <iframe id="preview" title="App preview" class="preview-frame ed-tall" sandbox="allow-scripts"></iframe>
    </div>
  </div>

  <div class="page-stack">
    <div class="form-row">
      <label class="field-label">Name<input type="text" id="appName" placeholder="App name"></label>
      <label class="field-label">Slug<input type="text" id="appSlugInput" placeholder="slug"></label>
      <label class="field-label">Description<input type="text" id="appDesc" placeholder="What does this app do?"></label>
      <label class="field-label">Tags<input type="text" id="appTags" placeholder="e.g. productivity"></label>
      <label class="field-label">Price (credits)<input type="number" id="appPrice" placeholder="0 = free" min="0" max="1000" title="Credits charged per use (0 = free)"></label>
    </div>
    <div class="form-actions">
      <button data-app-action="saveApp" class="btn">Save</button>
      <label class="check-label"><input type="checkbox" id="appPublic"> Public</label>
    </div>
  </div>
  <div class="d-flex between items-center">
    <span class="status-msg" id="statusMsg"></span>
  </div>
  <div class="d-flex between items-center text-sm text-muted">
    <span id="savedAt">%s</span>
    <span>%s</span>
  </div>
</div>

<script type="application/json" id="app-editor-state">%s</script>`, htmlpkg.EscapeString(a.Slug), aiPanel, savedAt, versionLink, state)
}
