package apps

import (
	"encoding/json"
	"fmt"
	htmlpkg "html"
	"strings"

	"mu/internal/quota"
)

// slugify turns a name into a URL-safe slug.
func slugify(s string) string {
	s = strings.ToLower(s)
	// Replace non-alphanumeric with hyphens
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') {
			b.WriteRune(c)
		} else if c == ' ' || c == '-' || c == '_' {
			b.WriteRune('-')
		}
	}
	result := strings.Trim(b.String(), "-")
	if len(result) > 50 {
		result = result[:50]
	}
	return strings.Trim(result, "-")
}

// editPageHTML renders the app editor: a code editor with live preview and a
// save bar. It is a manual editor — apps are generated by the constrained
// micro-app generator, but their HTML can still be hand-edited here.
func editPageHTML(a *App) string {
	escapedCode, _ := json.Marshal(a.HTML)
	escapedName, _ := json.Marshal(a.Name)
	escapedDesc, _ := json.Marshal(a.Description)
	escapedTags, _ := json.Marshal(a.Tags)
	escapedIcon, _ := json.Marshal(a.Icon)
	escapedSlug, _ := json.Marshal(a.Slug)

	// Ask-for-a-change panel. Editing the stored spec keeps everything the
	// instruction does not mention; regenerating from a description would not.
	aiPanel := fmt.Sprintf(`<form method="POST" action="/apps/%s/ai-edit" class="form ai-edit">
  <label for="instruction">Change it with AI</label>
  <div class="form-row">
    <input type="text" id="instruction" name="instruction" required
           placeholder="e.g. add a Notes field, or change the total to average">
    <button type="submit">Apply</button>
  </div>
  <p class="ai-edit-note">%d credits. Your current version is saved first — undo any change from <a href="/apps/%s/versions">versions</a>.</p>
</form>`, htmlpkg.EscapeString(a.Slug), quota.OperationCost(quota.OpAppEdit), htmlpkg.EscapeString(a.Slug))

	if a.Spec == nil {
		aiPanel = `<div class="form ai-edit"><p class="ai-edit-note">This app was built before AI edits were supported, so there is no spec to change. Fork it to get an editable copy, or edit the code directly below.</p></div>`
	}

	savedAt := "Last saved " + a.UpdatedAt.Format("2 Jan 2006 15:04")
	versionLink := ""
	if len(a.Versions) > 0 {
		v := a.Versions[len(a.Versions)-1]
		versionLink = fmt.Sprintf(`<a href="/apps/%s/versions" class="text-muted">v%d · %d versions</a>`,
			htmlpkg.EscapeString(a.Slug), v.Number, len(a.Versions))
	}

	return fmt.Sprintf(`


<div class="builder">
  <div class="d-flex between items-center mb-1 flex-wrap gap-2">
    <p class="card-desc m-0">Edit your app</p>
    <div class="d-flex gap-2 items-center text-sm">
      <a href="/apps/%s" class="mini-btn">Open App</a>
      <button onclick="deleteApp()" class="mini-btn btn-danger">Delete</button>
    </div>
  </div>

  %s

  <div class="form-row">
    <div class="ed-grow">
      <div class="code-header mb-2">
        <h3>Code</h3>
        <div class="form-actions">
          <button class="mini-btn" onclick="copyCode()">Copy</button>
        </div>
      </div>
      <textarea class="code-editor ed-tall" id="code" spellcheck="false"></textarea>
    </div>
    <div class="ed-grow">
      <div class="preview-header mb-2">
        <h3>Preview</h3>
        <button class="mini-btn" onclick="updatePreview()">Refresh</button>
      </div>
      <iframe id="preview" class="preview-frame ed-tall" allow="geolocation"></iframe>
    </div>
  </div>

  <div class="page-stack">
    <div class="form-row">
      <label class="field-label">Name<input type="text" id="appName" placeholder="App name"></label>
      <label class="field-label">Slug<input type="text" id="appSlugInput" placeholder="slug"></label>
      <label class="field-label">Description<input type="text" id="appDesc" placeholder="What does this app do?"></label>
      <label class="field-label">Tags<input type="text" id="appTags" placeholder="e.g. productivity"></label>
      <label class="field-label">Price (credits)<input type="number" id="appPrice" placeholder="0 = free" min="0" max="1000" title="Credits charged per use (0 = free)"></label>
    </div>
    <div class="form-actions">
      <button onclick="saveApp()" class="btn">Save</button>
      <label class="check-label"><input type="checkbox" id="appPublic"> Public</label>
    </div>
  </div>
  <div class="d-flex between items-center">
    <span class="status-msg" id="statusMsg"></span>
  </div>
  <div class="d-flex between items-center text-sm text-muted">
    <span id="savedAt">%s</span>
    <span>%s</span>
  </div>
</div>

<script>
var codeEl = document.getElementById('code');
var preview = document.getElementById('preview');
var appIcon = %s;
var editSlug = %s;

// Pre-populate fields
codeEl.value = %s;
document.getElementById('appName').value = %s;
document.getElementById('appSlugInput').value = editSlug;
document.getElementById('appDesc').value = %s;
document.getElementById('appTags').value = %s;
document.getElementById('appPublic').checked = %s;
document.getElementById('appPrice').value = %d;
showPreview();

codeEl.addEventListener('keydown', function(e) {
  if (e.key === 'Tab') {
    e.preventDefault();
    var start = this.selectionStart, end = this.selectionEnd;
    this.value = this.value.substring(0, start) + '  ' + this.value.substring(end);
    this.selectionStart = this.selectionEnd = start + 2;
  }
});

function showPreview() {
  var html = codeEl.value;
  if (!html.trim()) return;
  preview.style.display = '';
  preview.srcdoc = html;
}

function updatePreview() { showPreview(); }

function saveApp() {
  var name = document.getElementById('appName').value.trim();
  var newSlug = document.getElementById('appSlugInput').value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'').replace(/^-|-$/g,'');
  var desc = document.getElementById('appDesc').value.trim();
  var tags = (document.getElementById('appTags').value || '').trim();
  var html = codeEl.value.trim();
  if (!name) { document.getElementById('statusMsg').textContent = 'App name is required'; return; }
  if (!html) { document.getElementById('statusMsg').textContent = 'No code to save'; return; }

  // If slug changed, rename first
  if (newSlug && newSlug !== editSlug) {
    document.getElementById('statusMsg').textContent = 'Renaming...';
    fetch('/apps/' + editSlug, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ slug: newSlug })
    }).then(function(r){ return r.json(); }).then(function(data){
      if (data.error) { document.getElementById('statusMsg').textContent = data.error; return; }
      editSlug = data.slug || newSlug;
      document.getElementById('appSlugInput').value = editSlug;
      doSave();
    }).catch(function(e){ document.getElementById('statusMsg').textContent = e.message; });
    return;
  }
  doSave();
  function doSave() {
  document.getElementById('statusMsg').textContent = 'Saving...';
  fetch('/apps/' + editSlug, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: name, icon: appIcon, description: desc, tags: tags, html: html, public: document.getElementById('appPublic').checked, price: parseInt(document.getElementById('appPrice').value)||0 })
  })
  .then(function(r) {
    if (!r.ok) {
      return r.text().then(function(t) {
        try { var j = JSON.parse(t); throw new Error(j.error || 'Save failed'); }
        catch(e) { if (e.message) throw e; throw new Error('Save failed (status ' + r.status + ')'); }
      });
    }
    return r.json();
  })
  .then(function(data) {
    if (data.error) { document.getElementById('statusMsg').textContent = data.error; return; }
    var now = new Date();
    var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    var ts = now.getDate() + ' ' + months[now.getMonth()] + ' ' + now.getFullYear() + ' ' + String(now.getHours()).padStart(2,'0') + ':' + String(now.getMinutes()).padStart(2,'0');
    document.getElementById('savedAt').textContent = 'Last saved ' + ts;
    document.getElementById('statusMsg').textContent = 'Saved!';
    setTimeout(function() { document.getElementById('statusMsg').textContent = ''; }, 3000);
  })
  .catch(function(e) { document.getElementById('statusMsg').textContent = e.message || 'Save failed'; });
  } // end doSave
}

function copyCode() {
  navigator.clipboard.writeText(codeEl.value).then(function() {
    document.getElementById('statusMsg').textContent = 'Copied!';
    setTimeout(function() { document.getElementById('statusMsg').textContent = ''; }, 2000);
  });
}

function deleteApp() {
  if (!confirm('Delete this app? This cannot be undone.')) return;
  fetch('/apps/' + editSlug + '/delete', { method: 'POST' })
  .then(function(r) { if (r.ok) window.location.href = '/apps'; else throw new Error('Delete failed'); })
  .catch(function(e) { document.getElementById('statusMsg').textContent = e.message; });
}
</script>`, htmlpkg.EscapeString(a.Slug), aiPanel, savedAt, versionLink, escapedIcon, escapedSlug, escapedCode, escapedName, escapedDesc, escapedTags, fmt.Sprintf("%v", a.Public), a.Price)
}
