package service

import (
	"reflect"

	"go-micro.dev/v6/server"
)

// Docs says what each of a handler's endpoints does, keyed by method name. The
// text is written for a model, not a developer: it is what the agent reads when
// deciding which tool to call.
//
//	var docs = service.Docs{
//		"Headlines": "Read the latest news headlines",
//		"Search":    "Search news articles by topic or keyword",
//	}
//
//	service.Register("news", new(Server), docs)
//
// Register prefixes each key with the handler's type name. A method with no
// entry is caught by TestEveryEndpointIsDescribed rather than silently shipping
// without one.
//
// This exists because go-micro's own documentation cannot reach us. It fills
// endpoint metadata by locating a method's source file at runtime and parsing
// the Go doc comment (server/comments.go).
//
// That fails unconditionally here: handlers are registered as pointers
// (new(Server)) while their methods have value receivers, so reflection yields
// synthesised wrappers whose source file is "<autogenerated>" — the parse never
// reaches a real file.
//
// Fixing the receiver would not be enough either, because the mechanism needs
// the Go source tree to sit next to the binary at runtime. That happens to hold
// for the systemd deployment, which builds in place, and does not hold for the
// container image, which is a multi-stage build carrying only the binary. A
// tool description should not depend on how the binary was shipped.
//
// Without this, every tool the agent sees is described as "Call Search on news
// service", which is close to no description at all. Docs is deliberately data
// passed to Register rather than a method on the handler: go-micro treats every
// exported handler method as an RPC endpoint and logs an error for any that
// does not fit that signature.
type Docs map[string]string

// endpointDocs turns a Docs map into the go-micro handler option that writes
// those descriptions into the registry, where the agent's tool discovery reads
// them. Returns nil if there is nothing to publish.
func endpointDocs(h any, docs Docs) server.HandlerOption {
	prefix := handlerName(h)
	if prefix == "" || len(docs) == 0 {
		return nil
	}
	out := map[string]server.EndpointDoc{}
	for method, desc := range docs {
		if method == "" || desc == "" {
			continue
		}
		out[prefix+"."+method] = server.EndpointDoc{Description: desc}
	}
	if len(out) == 0 {
		return nil
	}
	return server.WithEndpointDocs(out)
}

// handlerName is the type name go-micro prefixes a handler's endpoints with —
// "Server" for both Server and *Server.
func handlerName(h any) string {
	t := reflect.TypeOf(h)
	if t == nil {
		return ""
	}
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	return t.Name()
}

// EndpointDescriptions returns each registered endpoint of a service with the
// description it publishes. Used by the tool surfaces and by the test that
// keeps every endpoint described.
func EndpointDescriptions(name string) map[string]string {
	ensure()
	svcs, err := reg.GetService(name)
	if err != nil || len(svcs) == 0 {
		return nil
	}
	out := map[string]string{}
	for _, s := range svcs {
		for _, ep := range s.Endpoints {
			if ep == nil || ep.Name == "" {
				continue
			}
			out[ep.Name] = ep.Metadata["description"]
		}
	}
	return out
}
