package maps

const directionsUI = `<form id="map-directions" class="card d-flex gap-2" style="flex-wrap:wrap">
{{csrf}}<input name="from" class="grow" placeholder="From" aria-label="Starting point" required><button type="button" id="map-start-here">Use my location</button>
<input name="to" class="grow" placeholder="Destination" aria-label="Destination" required>
<select name="mode" aria-label="Travel mode"><option value="walk">Walk</option><option value="drive">Drive</option><option value="cycle">Cycle</option><option value="transit">Public transport</option></select><button type="submit">Directions</button>
</form><div id="map-directions-result" aria-live="polite"></div>
<script>(function(){var form=document.getElementById('map-directions'),out=document.getElementById('map-directions-result');if(!form||form.dataset.wired)return;form.dataset.wired='1';var request=0;
document.getElementById('map-start-here').onclick=function(){if(!navigator.geolocation){out.textContent='Location is unavailable. Enter a starting point.';return;}navigator.geolocation.getCurrentPosition(function(p){form.elements.from.value=p.coords.latitude+','+p.coords.longitude;},function(){out.textContent='Could not get your location. Enter a starting point.';},{timeout:10000});};
form.onsubmit=async function(e){e.preventDefault();var id=++request;out.textContent='Finding directions…';try{var q=new URLSearchParams(new FormData(form)),r=await fetch('/routes',{method:'POST',body:q,headers:{Accept:'application/json'}}),d=await r.json();if(id!==request)return;if(!r.ok)throw new Error(d.error||'Directions are unavailable.');out.replaceChildren();if(d.estimate){out.textContent='Road directions are unavailable on this instance. A straight-line estimate is not navigation.';return;}var summary=document.createElement('p');summary.textContent=d.summary;out.appendChild(summary);var list=document.createElement('ol');(d.steps||[]).forEach(function(s){var item=document.createElement('li');item.textContent=s.Text;list.appendChild(item);});out.appendChild(list);document.getElementById('map').dispatchEvent(new CustomEvent('map-route',{detail:d.shape||[]}));}catch(e){if(id===request)out.textContent=e.message||'Could not load directions.';}};
})();</script>`
