package apps

import (
	"encoding/json"
	"fmt"
	htmlpkg "html"
	"strings"
)

// slugify turns a name into a URL-safe slug.
func slugify(s string) string {
	s = strings.ToLower(s)
	// Replace non-alphanumeric with hyphens
	var b strings.Builder
	for _, c := range s {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') {
			b.WriteRune(c)
		} else if c == ' ' || c == '-' || c == '_' {
			b.WriteRune('-')
		}
	}
	result := strings.Trim(b.String(), "-")
	if len(result) > 50 {
		result = result[:50]
	}
	return strings.Trim(result, "-")
}

// editPageHTML renders the app editor: a code editor with live preview and a
// save bar. It is a manual editor — apps are generated by the constrained
// micro-app generator, but their HTML can still be hand-edited here.
func editPageHTML(a *App) string {
	escapedCode, _ := json.Marshal(a.HTML)
	escapedName, _ := json.Marshal(a.Name)
	escapedDesc, _ := json.Marshal(a.Description)
	escapedTags, _ := json.Marshal(a.Tags)
	escapedIcon, _ := json.Marshal(a.Icon)
	escapedSlug, _ := json.Marshal(a.Slug)

	savedAt := "Last saved " + a.UpdatedAt.Format("2 Jan 2006 15:04")
	versionLink := ""
	if len(a.Versions) > 0 {
		v := a.Versions[len(a.Versions)-1]
		versionLink = fmt.Sprintf(`<a href="/apps/%s/versions" style="color:#999;">v%d · %d versions</a>`,
			htmlpkg.EscapeString(a.Slug), v.Number, len(a.Versions))
	}

	return fmt.Sprintf(`
<style>
.builder { display: flex; flex-direction: column; gap: 12px; }
.preview-area { display: flex; flex-direction: column; min-height: 60vh; }
.preview-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
.preview-header h3 { font-size: 14px; font-weight: 600; margin: 0; }
.preview-frame { flex: 1; border: 1px solid #e0e0e0; border-radius: 6px; background: #fff; min-height: 50vh; }
.code-toggle { padding: 4px 12px; border: 1px solid #e0e0e0; border-radius: 6px; background: #fff; color: #333; cursor: pointer; font-size: 12px; font-family: inherit; }
.code-toggle:hover { background: #f5f5f5; color: #111; }
.code-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }
.code-header h3 { font-size: 14px; font-weight: 600; margin: 0; }
.code-header .actions { display: flex; gap: 6px; }
.code-header .actions button { padding: 4px 12px; border: 1px solid #e0e0e0; border-radius: 6px; background: #fff; color: #333; cursor: pointer; font-size: 12px; font-family: inherit; }
.code-header .actions button:hover { background: #f5f5f5; color: #111; }
.code-editor { width: 100%%; min-height: 300px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 6px; font-family: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace; font-size: 13px; line-height: 1.5; resize: vertical; tab-size: 2; background: #fafafa; }
.save-bar { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
.save-bar input { padding: 8px 12px; border: 1px solid #e0e0e0; border-radius: 6px; font-family: inherit; font-size: 14px; color: #333; box-sizing: border-box; }
.save-bar input.name { flex: 1; min-width: 150px; }
.save-bar button { padding: 8px 20px; background: #000; color: #fff; border: none; border-radius: 6px; cursor: pointer; font-family: inherit; white-space: nowrap; }
.status-msg { font-size: 13px; color: #999; margin-left: 8px; }
@media (max-width: 768px) {
  .save-bar { flex-direction: column; align-items: stretch; }
  .save-bar input.name { width: 100%%; min-width: auto; }
  .save-bar input { width: 100%%; }
}
</style>

<div class="builder">
  <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:4px;flex-wrap:wrap;gap:8px">
    <p class="card-desc" style="margin:0">Edit your app</p>
    <div style="display:flex;gap:8px;align-items:center;font-size:13px">
      <a href="/apps/%s" style="color:#333;text-decoration:none;padding:4px 12px;border:1px solid #e0e0e0;border-radius:6px">Open App</a>
      <button onclick="deleteApp()" style="padding:4px 12px;border:1px solid #e0e0e0;border-radius:6px;background:#fff;color:#c00;cursor:pointer;font-size:13px;font-family:inherit">Delete</button>
    </div>
  </div>

  <div style="display:flex;gap:12px;flex-wrap:wrap;">
    <div style="flex:1;min-width:300px;">
      <div class="code-header" style="margin-bottom:6px;">
        <h3>Code</h3>
        <div class="actions">
          <button onclick="copyCode()">Copy</button>
        </div>
      </div>
      <textarea class="code-editor" id="code" spellcheck="false" style="min-height:50vh;"></textarea>
    </div>
    <div style="flex:1;min-width:300px;">
      <div class="preview-header" style="margin-bottom:6px;">
        <h3>Preview</h3>
        <button class="code-toggle" onclick="updatePreview()">Refresh</button>
      </div>
      <iframe id="preview" class="preview-frame" allow="geolocation" style="min-height:50vh;"></iframe>
    </div>
  </div>

  <div class="save-bar" style="display:grid;grid-template-columns:1fr auto;gap:8px 12px;align-items:end;">
    <div style="display:flex;gap:8px;flex-wrap:wrap;align-items:end;">
      <div style="flex:1;min-width:150px;">
        <label for="appName" style="font-size:12px;color:#666;display:block;margin-bottom:2px;">Name</label>
        <input class="name" type="text" id="appName" placeholder="App name" style="width:100%%;box-sizing:border-box;padding:8px 12px;border:1px solid #e0e0e0;border-radius:6px;font-family:inherit;font-size:14px;">
      </div>
      <div style="width:140px;">
        <label for="appSlugInput" style="font-size:12px;color:#666;display:block;margin-bottom:2px;">Slug</label>
        <input type="text" id="appSlugInput" placeholder="slug" style="width:100%%;box-sizing:border-box;padding:8px 12px;border:1px solid #e0e0e0;border-radius:6px;font-size:13px;color:#888;">
      </div>
      <div style="flex:1;min-width:120px;">
        <label for="appDesc" style="font-size:12px;color:#666;display:block;margin-bottom:2px;">Description</label>
        <input type="text" id="appDesc" placeholder="What does this app do?" style="width:100%%;box-sizing:border-box;padding:8px 12px;border:1px solid #e0e0e0;border-radius:6px;font-family:inherit;font-size:14px;">
      </div>
      <div style="width:140px;">
        <label for="appTags" style="font-size:12px;color:#666;display:block;margin-bottom:2px;">Tags</label>
        <input type="text" id="appTags" placeholder="e.g. productivity" style="width:100%%;box-sizing:border-box;padding:8px 12px;border:1px solid #e0e0e0;border-radius:6px;font-family:inherit;font-size:14px;">
      </div>
      <div style="width:130px;">
        <label for="appPrice" style="font-size:12px;color:#666;display:block;margin-bottom:2px;">Price (credits)</label>
        <input type="number" id="appPrice" placeholder="0 = free" style="width:100%%;box-sizing:border-box;padding:8px 12px;border:1px solid #e0e0e0;border-radius:6px;font-size:13px;" min="0" max="1000" title="Credits charged per use (0 = free)">
      </div>
      <label style="display:flex;align-items:center;gap:4px;font-size:13px;white-space:nowrap;padding:8px 0;"><input type="checkbox" id="appPublic" style="width:auto;margin:0"> Public</label>
    </div>
    <div style="display:flex;gap:8px;align-items:end;">
      <button onclick="saveApp()" style="padding:8px 20px;background:#000;color:#fff;border:none;border-radius:6px;cursor:pointer;font-family:inherit;white-space:nowrap;">Save</button>
    </div>
  </div>
  <div style="display:flex;justify-content:space-between;align-items:center;">
    <span class="status-msg" id="statusMsg"></span>
  </div>
  <div style="display:flex;justify-content:space-between;align-items:center;font-size:13px;color:#999;">
    <span id="savedAt">%s</span>
    <span>%s</span>
  </div>
</div>

<script>
var codeEl = document.getElementById('code');
var preview = document.getElementById('preview');
var appIcon = %s;
var editSlug = %s;

// Pre-populate fields
codeEl.value = %s;
document.getElementById('appName').value = %s;
document.getElementById('appSlugInput').value = editSlug;
document.getElementById('appDesc').value = %s;
document.getElementById('appTags').value = %s;
document.getElementById('appPublic').checked = %s;
document.getElementById('appPrice').value = %d;
showPreview();

codeEl.addEventListener('keydown', function(e) {
  if (e.key === 'Tab') {
    e.preventDefault();
    var start = this.selectionStart, end = this.selectionEnd;
    this.value = this.value.substring(0, start) + '  ' + this.value.substring(end);
    this.selectionStart = this.selectionEnd = start + 2;
  }
});

function showPreview() {
  var html = codeEl.value;
  if (!html.trim()) return;
  preview.style.display = '';
  preview.srcdoc = html;
}

function updatePreview() { showPreview(); }

function saveApp() {
  var name = document.getElementById('appName').value.trim();
  var newSlug = document.getElementById('appSlugInput').value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'').replace(/^-|-$/g,'');
  var desc = document.getElementById('appDesc').value.trim();
  var tags = (document.getElementById('appTags').value || '').trim();
  var html = codeEl.value.trim();
  if (!name) { document.getElementById('statusMsg').textContent = 'App name is required'; return; }
  if (!html) { document.getElementById('statusMsg').textContent = 'No code to save'; return; }

  // If slug changed, rename first
  if (newSlug && newSlug !== editSlug) {
    document.getElementById('statusMsg').textContent = 'Renaming...';
    fetch('/apps/' + editSlug, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ slug: newSlug })
    }).then(function(r){ return r.json(); }).then(function(data){
      if (data.error) { document.getElementById('statusMsg').textContent = data.error; return; }
      editSlug = data.slug || newSlug;
      document.getElementById('appSlugInput').value = editSlug;
      doSave();
    }).catch(function(e){ document.getElementById('statusMsg').textContent = e.message; });
    return;
  }
  doSave();
  function doSave() {
  document.getElementById('statusMsg').textContent = 'Saving...';
  fetch('/apps/' + editSlug, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: name, icon: appIcon, description: desc, tags: tags, html: html, public: document.getElementById('appPublic').checked, price: parseInt(document.getElementById('appPrice').value)||0 })
  })
  .then(function(r) {
    if (!r.ok) {
      return r.text().then(function(t) {
        try { var j = JSON.parse(t); throw new Error(j.error || 'Save failed'); }
        catch(e) { if (e.message) throw e; throw new Error('Save failed (status ' + r.status + ')'); }
      });
    }
    return r.json();
  })
  .then(function(data) {
    if (data.error) { document.getElementById('statusMsg').textContent = data.error; return; }
    var now = new Date();
    var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    var ts = now.getDate() + ' ' + months[now.getMonth()] + ' ' + now.getFullYear() + ' ' + String(now.getHours()).padStart(2,'0') + ':' + String(now.getMinutes()).padStart(2,'0');
    document.getElementById('savedAt').textContent = 'Last saved ' + ts;
    document.getElementById('statusMsg').textContent = 'Saved!';
    setTimeout(function() { document.getElementById('statusMsg').textContent = ''; }, 3000);
  })
  .catch(function(e) { document.getElementById('statusMsg').textContent = e.message || 'Save failed'; });
  } // end doSave
}

function copyCode() {
  navigator.clipboard.writeText(codeEl.value).then(function() {
    document.getElementById('statusMsg').textContent = 'Copied!';
    setTimeout(function() { document.getElementById('statusMsg').textContent = ''; }, 2000);
  });
}

function deleteApp() {
  if (!confirm('Delete this app? This cannot be undone.')) return;
  fetch('/apps/' + editSlug + '/delete', { method: 'POST' })
  .then(function(r) { if (r.ok) window.location.href = '/apps'; else throw new Error('Delete failed'); })
  .catch(function(e) { document.getElementById('statusMsg').textContent = e.message; });
}
</script>`, htmlpkg.EscapeString(a.Slug), savedAt, versionLink, escapedIcon, escapedSlug, escapedCode, escapedName, escapedDesc, escapedTags, fmt.Sprintf("%v", a.Public), a.Price)
}
